# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 676)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.BtnRAWFiles = QtWidgets.QPushButton(self.centralWidget)
        self.BtnRAWFiles.setGeometry(QtCore.QRect(110, 160, 51, 41))
        self.BtnRAWFiles.setObjectName("BtnRAWFiles")
        self.ToBeProcessedPath = QtWidgets.QListWidget(self.centralWidget)
        self.ToBeProcessedPath.setGeometry(QtCore.QRect(10, 200, 301, 21))
        self.ToBeProcessedPath.setObjectName("ToBeProcessedPath")
        self.RawFilesLabel = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel.setGeometry(QtCore.QRect(10, 170, 111, 16))
        self.RawFilesLabel.setObjectName("RawFilesLabel")
        self.LabelPROCFiles = QtWidgets.QLabel(self.centralWidget)
        self.LabelPROCFiles.setGeometry(QtCore.QRect(10, 240, 171, 16))
        self.LabelPROCFiles.setObjectName("LabelPROCFiles")
        self.BtnPathPROCFiles = QtWidgets.QPushButton(self.centralWidget)
        self.BtnPathPROCFiles.setGeometry(QtCore.QRect(180, 230, 51, 41))
        self.BtnPathPROCFiles.setObjectName("BtnPathPROCFiles")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setGeometry(QtCore.QRect(190, 630, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(10, 290, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ProcessedPath = QtWidgets.QListWidget(self.centralWidget)
        self.ProcessedPath.setGeometry(QtCore.QRect(10, 270, 301, 21))
        self.ProcessedPath.setObjectName("ProcessedPath")
        self.BtnReadCSV = QtWidgets.QPushButton(self.centralWidget)
        self.BtnReadCSV.setGeometry(QtCore.QRect(80, 310, 151, 41))
        self.BtnReadCSV.setObjectName("BtnReadCSV")
        self.RawFilesLabel_2 = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel_2.setGeometry(QtCore.QRect(170, 610, 171, 16))
        self.RawFilesLabel_2.setObjectName("RawFilesLabel_2")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 350, 321, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.RawFilesLabel_3 = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel_3.setGeometry(QtCore.QRect(380, 120, 101, 16))
        self.RawFilesLabel_3.setObjectName("RawFilesLabel_3")
        self.ListOfTextFound = QtWidgets.QListWidget(self.centralWidget)
        self.ListOfTextFound.setGeometry(QtCore.QRect(510, 140, 151, 221))
        self.ListOfTextFound.setObjectName("ListOfTextFound")
        self.RawFilesLabel_4 = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel_4.setGeometry(QtCore.QRect(520, 120, 141, 16))
        self.RawFilesLabel_4.setObjectName("RawFilesLabel_4")
        self.RawFilesLabel_5 = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel_5.setGeometry(QtCore.QRect(10, 10, 311, 16))
        self.RawFilesLabel_5.setTextFormat(QtCore.Qt.RichText)
        self.RawFilesLabel_5.setWordWrap(False)
        self.RawFilesLabel_5.setObjectName("RawFilesLabel_5")
        self.RawFilesLabel_6 = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel_6.setGeometry(QtCore.QRect(10, 70, 311, 21))
        self.RawFilesLabel_6.setObjectName("RawFilesLabel_6")
        self.RawFilesLabel_7 = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel_7.setGeometry(QtCore.QRect(10, 90, 311, 21))
        self.RawFilesLabel_7.setObjectName("RawFilesLabel_7")
        self.RawFilesLabel_8 = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel_8.setGeometry(QtCore.QRect(10, 40, 311, 16))
        self.RawFilesLabel_8.setObjectName("RawFilesLabel_8")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 130, 321, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(320, 140, 20, 221))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.TextPerSensorTable = QtWidgets.QTableWidget(self.centralWidget)
        self.TextPerSensorTable.setGeometry(QtCore.QRect(10, 410, 321, 191))
        self.TextPerSensorTable.setRowCount(1)
        self.TextPerSensorTable.setColumnCount(2)
        self.TextPerSensorTable.setObjectName("TextPerSensorTable")
        self.BtnReplaceText = QtWidgets.QPushButton(self.centralWidget)
        self.BtnReplaceText.setGeometry(QtCore.QRect(10, 610, 151, 41))
        self.BtnReplaceText.setObjectName("BtnReplaceText")
        self.RawFilesLabel_9 = QtWidgets.QLabel(self.centralWidget)
        self.RawFilesLabel_9.setGeometry(QtCore.QRect(80, 380, 171, 16))
        self.RawFilesLabel_9.setObjectName("RawFilesLabel_9")
        self.BtnGenerateMtellFiles = QtWidgets.QPushButton(self.centralWidget)
        self.BtnGenerateMtellFiles.setGeometry(QtCore.QRect(350, 410, 181, 41))
        self.BtnGenerateMtellFiles.setObjectName("BtnGenerateMtellFiles")
        self.ListOfSensors = QtWidgets.QListWidget(self.centralWidget)
        self.ListOfSensors.setGeometry(QtCore.QRect(350, 140, 151, 221))
        self.ListOfSensors.setObjectName("ListOfSensors")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BtnRAWFiles.setText(_translate("MainWindow", "..."))
        self.RawFilesLabel.setText(_translate("MainWindow", "CSV file location"))
        self.LabelPROCFiles.setText(_translate("MainWindow", "Processed CSV file location"))
        self.BtnPathPROCFiles.setText(_translate("MainWindow", "..."))
        self.BtnReadCSV.setText(_translate("MainWindow", "Read CSV File"))
        self.RawFilesLabel_2.setText(_translate("MainWindow", "Processing, please wait..."))
        self.RawFilesLabel_3.setText(_translate("MainWindow", "List of Sensors"))
        self.RawFilesLabel_4.setText(_translate("MainWindow", "Text found in CSV file"))
        self.RawFilesLabel_5.setText(_translate("MainWindow", "Aspen Technoly Inc."))
        self.RawFilesLabel_6.setText(_translate("MainWindow", "This tool will find text for each sensor and let user"))
        self.RawFilesLabel_7.setText(_translate("MainWindow", "replace such text (bad data) with numbers"))
        self.RawFilesLabel_8.setText(_translate("MainWindow", "Data Wrangling Tool"))
        self.TextPerSensorTable.setSortingEnabled(True)
        self.BtnReplaceText.setText(_translate("MainWindow", "Replace Text"))
        self.RawFilesLabel_9.setText(_translate("MainWindow", "Replace text with a number"))
        self.BtnGenerateMtellFiles.setText(_translate("MainWindow", "Generate Mtell CSV files"))

